dist: xenial

notifications:
  email: false

git:
  depth: 5
  submodules: false

language: bash
services: docker

before_script:
  - cd "$IMAGE"
#   - |
#     image_clean=${IMAGE//_/};
#     image_name=$(echo $image_clean | cut -f1 -d-);
#     image_tag=$(echo $STR | cut -f2 -d-)
  - image_name="ai-python:${IMAGE//_/}"

script:
  - docker build -t "$image_name" .

after_script:
  - cd "$TRAVIS_BUILD_DIR"
  - docker images
  - docker run "$image_name" sh -c "pip list"
#   - echo "echo 'test'" | docker run -i "$image_name" sh -
  - docker run -i "$image_name" python < test.py

jobs:
  allow_failures:
    - stage: Test Master Docker Images
  include:
    - &master-build
      # Master builds -- all can fail
      stage: Test Master Docker Images
      if: branch = master
      env: IMAGE="_experimental"
    - <<: *master-build
      env: IMAGE="_experimental-dev"
    - <<: *master-build
      env: IMAGE="_versioned"
    - <<: *master-build
      env: IMAGE="_versioned-dev"
    - &tag-build
      # Tag builds -- none can fail
      stage: Test Tagged Docker Images
      if: tag IS present
      env: IMAGE="_versioned"
    - <<: *tag-build
      env: IMAGE="_versioned-dev"
